### ISSUE TITLE
Block maken voor CO2 sensor

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-blocks#26]
De sensor gebruikt de SGP30:
https://nl.mouser.com/datasheet/2/682/Sensirion_Gas_Sensors_Datasheet_SGP30-2320451.pdf

Mogelijk issue: De eerste 15 readings geven '0' waarden terug (tijdens calibratie)

**Comment by JeftadeGraaf** [comment]
Gaat dit over de gassensor?

**Comment by JeftadeGraaf** [comment]
Ik heb inmiddels het blok en de code toegevoegd. Nu moet alleen de library nog toegevoegd worden aan de toegevoegde librarys

**Comment by rmoesbergen** [comment]
> Ik heb inmiddels het blok en de code toegevoegd. Nu moet alleen de library nog toegevoegd worden aan de toegevoegde librarys

Nice! Zou je het block zo willen maken dat hij als 'input value' bruikbaar is in bijvoorbeeld een if() of een "Toon op scherm" blok? Je kunt als voorbeeld evt. andere "Lees" blokken gebruiken (kompas, gesture, afstand, etc.). Je hoeft dan ook niet zelf iets met Serial te doen, dat kun je dan aan de gebruiker over laten.

De library toevoegen voor compileren kun je hier doen:
https://github.com/leaphy-robotics/leaphy-webbased/blob/main/src/app/state/app.state.ts

Daar wordt per robot type een array gemaakt met de libraries die voor dat robot type nodig zijn. Olivier maakt nog een excel sheet met een overzicht van welke blocks er bij welke robot moeten.

**Comment by JeftadeGraaf** [comment]
Inmiddels gefixt, heb geprobeerd om bij robot type erbij te voegen maar kreeg alsnog een error dat de library niet aanwezig was

**Comment by rmoesbergen** [comment]
> Inmiddels gefixt, heb geprobeerd om bij robot type erbij te voegen maar kreeg alsnog een error dat de library niet aanwezig was

Kun je een PR maken? Die hele serial kan er uit, anders krijgen we dubbele serial.begin() statements. En er staat nog een debug console.log() in. Als de sensor niet werkt kun je dan een waarde -1 returnen of iets dergelijks in plaats van een while(1) ?

**Comment by rmoesbergen** [comment]
De library heet `Adafruit_SGP30_Sensor` trouwens, zo te zien heb je `Adafruit_SGP30` geprobeerd, maar die bestaat niet.

**Comment by JeftadeGraaf** [comment]
yes, alles toegevoegd. de library is Adafruit SGP30 Sensor. Ik zal meteen ook het indelen doen. voeg ik hem daar erbij

**Comment by rmoesbergen** [comment]
Alleen nog ff de NL vertaling erbij en dan is ie wat mij betreft helemaal prima.
