### ISSUE TITLE
[bug] demo for testing blocks not working

### ISSUE THREAD

**Issue by JeftadeGraaf** [leaphy-robotics/leaphy-blocks#48]
You could first test your blocks by putting them in demos\code\index.html. Now your just getting a blank screen:

![image](https://github.com/leaphy-robotics/leaphy-blocks/assets/91546552/a8fb796d-fb0e-4579-b4bd-fd4972f5f71f)

**Comment by koen1711** [comment]
Demo's can just be removed, as we now test in a local version of leaphy-webbased
