### ISSUE TITLE
[enhancement] Make blocks portable for other chips

### ISSUE THREAD

**Issue by rmoesbergen** [leaphy-robotics/leaphy-blocks#88]
Some (most) of the blocks currently use code that includes 'avr.h' and uses AVR specific functions. This means they won't run on the ESP32 or RP2040. This ticket is to fix those blocks and use more generic libraries/functions. While doing this, we can also move as much code as possible out of the leaphy c++ arduino libraries.

**Comment by koen1711** [comment]
I'm starting development now
